version: "3.9"
services:
  pia:
    image: thrnz/docker-wireguard-pia
    container_name: pia
    volumes:
      - $DOCKER_DIR/data/pia:/pia
      - $DOCKER_DIR/shared/pia:/pia-shared
    networks:
      - socket_proxy
      - traefik_proxy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LOC=us_chicago
      - USER=${PIA_USER}
      - PASS=${PIA_PASSWORD}
      - LOCAL_NETWORK=192.168.1.0/24
      # - PORT_FORWARDING=1
      - PORT_PERSIST=1
      # - PORT_SCRIPT=/pia-shared/portupdate-qbittorrent.sh
      # - EXIT_ON_FATAL=1
    ports:
      - 8085:8085 # qbittorrent web ui
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 8087:8080 # sabnzbd
    restart: always
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    labels:
      - readme.description=A Docker container for using WireGuard with PIA.
      - readme.links.docker=https://hub.docker.com/r/thrnz/docker-wireguard-pia
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qbittorrent-rtr.entrypoints=https"
      - "traefik.http.routers.qbittorrent-rtr.rule=Host(`qbit.${DOMAIN_NAME}`)"
      ## Middlewares
      - "traefik.http.routers.qbittorrent-rtr.middlewares=rate-limit@file, chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc"
      - "traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8085"
      ## HTTP Routers
      - "traefik.http.routers.sabnzbd-rtr.entrypoints=https"
      - "traefik.http.routers.sabnzbd-rtr.rule=Host(`sab.${DOMAIN_NAME}`)"
      ## Middlewares
      - "traefik.http.routers.sabnzbd-rtr.middlewares=rate-limit@file, chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.sabnzbd-rtr.service=sabnzbd-svc"
      - "traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080"
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      pia: 
        condition: service_healthy
    network_mode: service:pia
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8085
    volumes:
      - $DOCKER_DIR/configs/qbittorrent:/config
      - $DOWNLOADS_DIR/torrents:/downloads/torrents
    restart: always

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    depends_on:
      pia: 
        condition: service_healthy
    network_mode: service:pia
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - $DOCKER_DIR/configs/sabnzbd:/config
      - $DOWNLOADS_DIR/usenet:/downloads #optional
    restart: always

networks:
  traefik_proxy:
    external: true
  socket_proxy:
    external: true
