version: "3.9"
services:

  ########## Docker Utilities ##########

  ## Ouroboros
  # https://hub.docker.com/r/pyouroboros/ouroboros/
  # https://github.com/pyouroboros/ouroboros/wiki
  ouroboros:
    container_name: ouroboros
    image: pyouroboros/ouroboros:latest
    restart: always
    networks:
      - traefik_proxy
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Connect to docker-socket-proxy tcp://docker-socket-proxy:2375
      - $DOCKER_DIR/configs/ouroboros:/root/.docker/config.json:ro
    environment:
      - TZ
      - CLEANUP=true
      - CRON="0 5 * * 1" # Run at 5AM every Monday
      - LATEST=false
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - NOTIFIERS=${DISCORD_NOTIFY} # Discord Webhook URL
      - RUN_ONCE=false # Default false
      - DRY_RUN=false # Best used with RUN_ONCE for config testing

  ## Who Am I?? - Show Headers
  whoami:
    container_name: whoami
    image: containous/whoami:latest
    restart: always
    networks:
      - traefik_proxy
    environment:
      - WHOAMI_NAME
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.whoami-rtr.entrypoints=https"
      - "traefik.http.routers.whoami-rtr.rule=Host(`whoami.${DOMAIN_NAME}`)"
      ## Middlewares
      - "traefik.http.routers.whoami-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.whoami-rtr.service=whoami-svc"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
  socket_proxy:
    external: true
