version: "3.9"
services:

  ########## Games ##########

  project-zomboid:
    container_name: project-zomboid
    image: cyrale/project-zomboid
    restart: unless-stopped
    environment:
      SERVER_NAME: "pzserver"
      SERVER_PASSWORD: ${PZSERVER_SERVER_PASSWORD}
      ADMIN_PASSWORD: ${PZSERVER_ADMIN_PASSWORD}
      SERVER_PUBLIC_NAME: "LouHome-PZ"
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262-16278:16262-16278"
      - "27015:27015"
    volumes:
      - $DOCKER_DIR/data/project-zomboid/server-data:/server-data
      - $DOCKER_DIR/configs/project-zomboid/server-files:/server-files
    # labels:
    #   - "traefik.enable=true"
    #   ## HTTP Routers
    #   - "traefik.http.routers.pzserver-rtr.entrypoints=https"
    #   - "traefik.http.routers.pzserver-rtr.rule=Host(`pzserver.${DOMAIN_NAME}`)"
    #   ## Middlewares
    #   - "traefik.http.routers.pzserver-rtr.middlewares=chain-noauth@file"
    #   ## HTTP Services
    #   - "traefik.http.routers.pzserver-rtr.service=pzserver-svc"
    #   - "traefik.http.services.pzserver-svc.loadbalancer.server.port=16261"

networks:
  traefik_proxy:
    external: true
  socket_proxy:
    external: true
