
services:

  ########## Media and Media Requests ##########
  ## Doplarr
  doplarr:
    image: lscr.io/linuxserver/doplarr:latest
    container_name: doplarr
    networks:
      - traefik_proxy
    environment:
      - PUID
      - PGID
      - TZ
      - DISCORD__TOKEN=${DISCORD_TOKEN}
      - OVERSEERR__API=${OVERSEER_API_KEY}
      - OVERSEERR__URL=https://overseerr.${DOMAIN_NAME}
      # - RADARR__API=
      # - RADARR__URL=
      # - SONARR__API=
      # - SONARR__URL=
      - DISCORD__MAX_RESULTS=25 #optional
      - DISCORD__REQUESTED_MSG_STYLE=:plain #optional
      - SONARR__QUALITY_PROFILE= #optional
      - RADARR__QUALITY_PROFILE= #optional
      - SONARR__ROOTFOLDER= #optional
      - RADARR__ROOTFOLDER= #optional
      - SONARR__LANGUAGE_PROFILE= #optional
      - OVERSEERR__DEFAULT_ID= #optional
      - PARTIAL_SEASONS=true #optional
      - LOG_LEVEL=:info #optional
      - JAVA_OPTS= #optional
    volumes:
      - $DOCKER_DIR/configs/doplarr:/config
    restart: unless-stopped

  ## Overseerr
  overseerr:
    # user: $PUID
    image: hotio/overseerr:nightly
    container_name: overseerr
    networks:
      - traefik_proxy
    environment:
      - PUID
      - PGID
      - TZ
      - UMASK=002
    volumes:
      - $DOCKER_DIR/configs/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.overseerr-rtr.entrypoints=https"
      - "traefik.http.routers.overseerr-rtr.rule=Host(`overseerr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.overseerr-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.overseerr-rtr.middlewares=chain-noauth@file"
      ## HTTP Services
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"

  ## Plex Media Server
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: always
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    networks:
      traefik_proxy:
        ipv4_address: 192.168.50.200 # Set a static IP for tautulli to connect to
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      # - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKER_DIR/configs/plex:/config
      - $MEDIA_DIR/movies:/MOVIES:ro
      - $MEDIA_DIR/tv:/TV:ro
      - $MEDIA_DIR/music:/MUSIC:ro
    environment:
      - PUID
      - PGID
      - TZ
      # - ADVERTISE_IP=10.0.10.30,https://plex.${DOMAIN_NAME}:443
      - ALLOWED_NETWORKS=10.0.10.0/24,10.0.1.0/24,10.0.20.0/24,172.16.0.0/16
      # - PLEX_CLAIM=
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.plex-rtr.entrypoints=https"
      - "traefik.http.routers.plex-rtr.rule=Host(`plex.${DOMAIN_NAME}`)"
      - "traefik.http.routers.plex-rtr.priority=10"
      ## Middlewares
      - "traefik.http.routers.plex-rtr.middlewares=plex-headers"
      - "traefik.http.middlewares.plex-headers.headers.accesscontrolallowmethods=GET, OPTIONS, PUT"
      - "traefik.http.middlewares.plex-headers.headers.accesscontrolalloworiginlist=https://${DOMAIN_NAME}"
      - "traefik.http.middlewares.plex-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.plex-headers.headers.addvaryheader=true"
      #      - "traefik.http.middlewares.plex-headers.headers.allowedhosts=plex.${DOMAIN_NAME}"
      - "traefik.http.middlewares.plex-headers.headers.hostsproxyheaders=X-Forwarded-Host"
      #      - "traefik.http.middlewares.plex-headers.headers.sslhost=plex.${DOMAIN_NAME}"
      #      - "traefik.http.middlewares.plex-headers.headers.sslforcehost=true"
      #      - "traefik.http.middlewares.plex-headers.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.plex-headers.headers.stsseconds=63072000"
      - "traefik.http.middlewares.plex-headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.plex-headers.headers.stspreload=true"
      - "traefik.http.middlewares.plex-headers.headers.forcestsheader=true"
      #      - "traefik.http.middlewares.plex-headers.headers.framedeny=true"
      - "traefik.http.middlewares.plex-headers.headers.customframeoptionsvalue=allow-from https:${DOMAIN_NAME}" # This option overrides FrameDeny
      - "traefik.http.middlewares.plex-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.plex-headers.headers.browserxssfilter=true"
      #      - "traefik.http.middlewares.plex-headers.headers.contentsecuritypolicy=frame-ancestors 'none'; object-src 'none'; base-uri 'none';"
      - "traefik.http.middlewares.plex-headers.headers.referrerpolicy=same-origin"
      - "traefik.http.middlewares.plex-headers.headers.customresponseheaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex,"
      ## HTTP Services
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
      ## Forward Auth for Web
      - "traefik.http.routers.plexWeb-rtr.entrypoints=https"
      - "traefik.http.routers.plexWeb-rtr.rule=(Host(`plex.${DOMAIN_NAME}`) && PathPrefix(`/web/`))"
      - "traefik.http.routers.plexWeb-rtr.priority=20"
      - "traefik.http.routers.plexWeb-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.plexWeb-rtr.service=plex-svc"

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    networks:
      - traefik_proxy
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID
      - PGID
      - TZ
      # - PASSWORD= #optional
      # - CLI_ARGS= #optional
    volumes:
      - $DOCKER_DIR/configs/calibre/config:/config
      - $DOCKER_DIR/configs/calibre/uploads:/uploads #change before the ':'
      - $DOCKER_DIR/configs/calibre/plugins:/plugins #change before the ':'
      - $MEDIA_DIR/books/CalibreLibrary:/CalibreLibrary #this is where your ebooks will end up
    ports:
      - 8281:8080
      - 8282:8181
      - 8283:8081      
    restart: always
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.calibre-rtr.entrypoints=https"
      - "traefik.http.routers.calibre-rtr.rule=Host(`calibre.${DOMAIN_NAME}`)"
      - "traefik.http.routers.calibre-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.calibre-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.calibre-rtr.service=calibre-svc"
      - "traefik.http.services.calibre-svc.loadbalancer.server.port=5013"    

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    networks:
      - traefik_proxy    
    container_name: calibre-web
    environment:
      - PUID
      - PGID
      - TZ
      # - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - $DOCKER_DIR/configs/calibre-web/config:/config
      - $MEDIA_DIR/books/CalibreLibrary:/books
    ports:
      - 8083:8083
    restart: always
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.calibre-web-rtr.entrypoints=https"
      - "traefik.http.routers.calibre-web-rtr.rule=Host(`calibreweb.${DOMAIN_NAME}`)"
      - "traefik.http.routers.calibre-web-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.calibre-web-rtr.middlewares=chain-noauth@file"
      ## HTTP Services
      - "traefik.http.routers.calibre-web-rtr.service=calibre-web-svc"
      - "traefik.http.services.calibre-web-svc.loadbalancer.server.port=8083"        

networks:
  traefik_proxy:
    external: true
  socket_proxy:
    external: true
