# Use this command and change the user and password:
# echo $(htpasswd -nb user password)

# This is just an example of using basic login auth. Not currently enabled on this setup.
[http.middlewares]
  [http.middlewares.basic-auth.basicAuth]
    users = [
      "alex:$pswd123",
    ]
