  [http.middlewares.chain-oauth]
    [http.middlewares.chain-oauth.chain]
      middlewares = [ "rate-limit", "secure-headers", "ssl-redirect", "oauth"]

    [http.middlewares.chain-noauth.chain]
      middlewares = [ "rate-limit", "ssl-redirect", "secure-headers"]

    [http.middlewares.basic-chain.chain]
      middlewares = ["secure-headers", "basic-auth"]
